from django.contrib import admin
from django.urls import path, include
from invoices import views

urlpatterns = [
    path('admin/', admin.site.urls),  # Django admin URL
    path('api/', include('invoices.urls')),
    path('invoices/', views.get_all_invoices, name='get_all_invoices'),
    path('full_data/', views.get_full_data, name='get_full_data'),
    path('process_uploaded_csv/', views.process_uploaded_csv, name='process_uploaded_csv'),
    path('process_update_csv/', views.process_update_csv, name='process_update_csv'),
    path('create-comment/', views.create_comment, name='create-comment'),
    path('create-sales/', views.create_sales, name='create-sales'),
    path('create_customer_name/', views.create_customer_name, name='create_customer_name'),
    path('comments/', views.get_all_comments, name='get_all_comments'),
    path('invoice_paid/', views.update_invoice_paid_status, name='update_invoice_paid_status'),
    path('invoice_acceptance/', views.new_invoice_acceptance, name='new_invoice_acceptance'),
    path('bulk_invoice_acceptance/', views.bulk_invoice_acceptance, name='bulk_invoice_acceptance'),
    path('invoice_old_paid/', views.old_invoice_acceptance, name='old_invoice_acceptance'),
    path('paid_invoices/', views.get_paid_invoices, name='get_paid_invoices'),
    path('to_do_invoices/', views.get_to_do_invoices, name='get_to_do_invoices'),
    path('pending_invoices/', views.get_pending_invoices, name='get_pending_invoices'),
    path('review_invoices/', views.get_review_invoices, name='get_review_invoices'),
    path('invoice_sales_p/', views.update_invoice_sales_person, name='invoice_sales_person'),
    path('login/', views.login, name='login'),
    path('sales/', views.get_all_sales, name='get_all_sales'),
    path('accountants/', views.get_all_accountants, name='get_all_accountants'),
    path('sales_persons/', views.get_all_sales_persons, name='get_all_sales_persons'),
    path('manager_1/', views.manager_1, name='manager_1'),
    path('manager_2/', views.manager_2, name='manager_2'),
    path('manager_3/', views.manager_3, name='manager_3'),
    path('manager_4/', views.manager_4, name='manager_4'),
    path('all_users/', views.all_users, name='all_users'),
    path('create_accountant/', views.create_accountant, name='create_accountant'),
    path('create_sales_person/', views.create_sales_person, name='create_sales_person'),
    path('update_target_collections/', views.update_target_collections, name='update_target_collections'),
    path('get_customer/', views.get_customer_info, name='get_customer'),
    path('get_invoice/', views.get_invoice_info, name='get_invoice'),
    path('get_create_comment/', views.get_create_comment_info, name='get_create_comment'),
    # path('fetch_vouchers/', views.fetch_vouchers, name='fetch_vouchers'),
    path('fetch_html_data/', views.fetch_html_data, name='fetch_html_data'),
    path('create_account/', views.create_manager, name='storing_manager_details'),
    path('manager_data/', views.get_manager_data, name='manager_Data'),
    path('manager_customer_data/', views.get_manager_customer_data, name='manager_customer_data'),
    path('accountant_customer_data/', views.get_accountant_customer_data, name='accountant_customer_data'),
    path('accountant_pending_customer_data/', views.get_accountant_pending_customer_data, name='accountant_pending_customer_data'),
    path('manager_invoice_data/', views.get_manager_invoice_data, name='manager_invoice_data'),
    path('accountant_invoice_data/', views.get_accountant_invoice_data, name='accountant_invoice_data'),
    path('accountant_pending_invoice_data/', views.get_accountant_pending_invoice_data, name='accountant_pending_invoice_data'),
    path('accountant_paid_invoice_data/', views.get_accountant_paid_invoice_data, name='accountant_paid_invoice_data'),
    path('accountant_comment_data/', views.get_accountant_comment_data, name='accountant_comment_data'),
    path('customer_credit_period/', views.customer_credit_period, name='customer_credit_period'),
    path('customer_name_number/', views.customer_name_number, name='customer_name_number'),
    path('manager_dashboard_data/', views.manager_dashboard_data, name='manager_dashboard_data'),
]
