# Generated by Django 5.0.1 on 2024-10-27 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('optimal_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('threshold_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('over_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoices', models.CharField(max_length=100)),
                ('credit_period', models.IntegerField(blank=True, default=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('manager', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_manager', to='invoices.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('manager', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_person_manager', to='invoices.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('target_collection', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('business', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_assigned_to', to='invoices.business')),
                ('manager', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_manager', to='invoices.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='name_customer', to='invoices.customers')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='name_user', to='invoices.users')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('ref_no', models.CharField(max_length=100)),
                ('pending', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('days_passed', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('new', models.BooleanField(default=False)),
                ('old', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to='invoices.customers')),
                ('sales_person', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_sales_p', to='invoices.sales_persons')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_user', to='invoices.users')),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer_user', to='invoices.users'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('invoice_list', models.CharField(blank=True, max_length=1000, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('amount_promised', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('promised_date', models.DateField(blank=True, null=True)),
                ('follow_up_time', models.TimeField(blank=True, null=True)),
                ('comment_paid', models.BooleanField(default=False, null=True)),
                ('flag_to_manager', models.BooleanField(default=False, null=True)),
                ('invoice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_comments', to='invoices.customers')),
                ('sales_person', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_sales_pz', to='invoices.sales_persons')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments_user', to='invoices.users')),
            ],
        ),
    ]
