# Generated by Django 5.0.1 on 2024-05-04 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('optimal_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('threshold_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('over_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoices', models.CharField(max_length=100)),
                ('promised_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('promised_date', models.DateField(blank=True, null=True)),
                ('sales_person', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('ref_no', models.CharField(max_length=100)),
                ('pending', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('days_passed', models.IntegerField(default=0)),
                ('invoice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to='invoices.customers')),
            ],
        ),
    ]
