# Generated by Django 5.0.1 on 2024-05-04 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('date', models.DateField(blank=True, null=True)),
                ('invoice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_comments', to='invoices.customers')),
                ('reference', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_comments', to='invoices.invoice')),
            ],
        ),
    ]
