# Generated by Django 5.0.1 on 2024-05-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='reference',
            field=models.CharField(max_length=100),
        ),
    ]
