# Generated by Django 5.0.1 on 2024-11-08 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_manager_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager_instructions',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager_instructions',
            name='invoice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instruction_manager', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='manager_instructions',
            name='manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='man', to='invoices.manager'),
        ),
        migrations.AlterField(
            model_name='manager_instructions',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instruction_customer', to='invoices.customers'),
        ),
        migrations.AlterField(
            model_name='manager_instructions',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use', to='invoices.users'),
        ),
    ]
