# Generated by Django 5.0.1 on 2024-11-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_manager_instructions_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_paid',
            new_name='comment_status',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='flag_to_manager',
        ),
    ]
