# Generated by Django 5.0.1 on 2024-05-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_comments_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
