# Generated by Django 5.0.1 on 2024-11-14 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_rename_comment_paid_comments_comment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='optimal_due',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='threshold_due',
        ),
    ]
