# Generated by Django 5.0.1 on 2024-11-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_customers_optimal_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='amount_promised',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
