# Generated by Django 5.0.1 on 2024-05-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_rename_comment_comments_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='amount_promised',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
