# Generated by Django 5.0.1 on 2025-05-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_comments_amount_promised'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='business',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
