# Generated by Django 5.0.1 on 2025-07-14 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_remove_users_business_delete_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag_to_Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('invoice_list', models.CharField(blank=True, max_length=1000, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('promised_date', models.DateField(blank=True, null=True)),
                ('invoice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='invoices.customers')),
                ('sales_person', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.sales_persons')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='invoices.users')),
            ],
        ),
    ]
