# Generated by Django 5.0.1 on 2025-08-10 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_flag_to_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager_instructions',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='manager_instructions',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='manager_instructions',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='manager_instructions',
            name='user',
        ),
        migrations.DeleteModel(
            name='Flag_to_Manager',
        ),
        migrations.DeleteModel(
            name='Manager_Instructions',
        ),
    ]
