# Generated by Django 5.0.1 on 2024-05-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_comments_paid_customers_premium_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
