# Generated by Django 5.0.1 on 2024-05-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_comments_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
