# Generated by Django 5.0.1 on 2024-05-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_remove_comments_paid_remove_comments_paid_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
