# Generated by Django 5.0.1 on 2024-06-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_users_alter_comments_amount_promised_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='paid',
        ),
    ]
