# Generated by Django 5.0.1 on 2024-06-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_remove_comments_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='paid_date',
        ),
    ]
