# Generated by Django 5.0.1 on 2024-06-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_remove_comments_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='follow_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
