# Generated by Django 5.0.1 on 2024-06-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_comments_comment_paid_comments_follow_up_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
