# Generated by Django 5.0.1 on 2024-06-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='review',
            field=models.BooleanField(default=False),
        ),
    ]
