# Generated by Django 5.0.1 on 2024-06-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_rename_review_invoice_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='credit_period',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
