# Generated by Django 5.0.1 on 2024-06-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0025_alter_customers_credit_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='to_do',
            field=models.BooleanField(default=False),
        ),
    ]
