# Generated by Django 5.0.1 on 2024-06-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0028_comments_deleted_at_comments_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='name',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='name',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='sales_persons',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='sales_persons',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='users',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_deleted',
        ),
    ]
